### ISSUE TITLE
ゼミ論中間発表（12/2）

### ISSUE THREAD

**Issue by kouki-T** [furuhashilab/gsc2019_Kouki-Takesue#2]
ゼミ論中間発表のコメント欄です。上手に説明できるとは到底思えないのでわからないところは気軽にコメントしてください。

**Comment by ShogoHirasawa** [comment]
人生ってなんですか？

**Comment by mapconcierge** [comment]
* heroku 依存を無課金でどうクリアするか

**Comment by 22hero1072** [comment]
WTFPLライセンスになさってみては？

**Comment by kouki-T** [comment]
> 人生ってなんですか？

哲学ゾンビという言葉があるように、何かを生み出さないと生きているとは言えないのかもしれないと個人的に思いました。

**Comment by mapconcierge** [comment]
* ライセンスを最終的にどれにするかは要検討
https://github.com/furuhashilab/gsc2019_Kouki-Takesue/blob/master/LICENSE

**Comment by shuntacarp** [comment]
どうすれば”強い男”になれますか。

**Comment by halgraphic** [comment]
プロフェッショナルとは？
